"""
record.py — decision record check + verified-facts block. Standard library only.

Each issue leaves a decision record `<dir>/<NNNN>-<slug>.md` (see docs/DECISION_RECORDS.md).
The agent writes the rationale; this module

  1. locates the record and checks it was written/updated by this change,
  2. checks it for consistency with the change (deterministic: required sections, Status,
     length, references to code that does not exist, changed components the record never
     mentions, unexplained out-of-scope changes, unmentioned removed symbols, verification
     claims naming tests that do not exist),
  3. appends (or replaces) a tool-generated "Verified facts" block at the end of the record
     (working-tree mode only; the runner then commits it with the change).

    check_record(repo, cfg=..., issue=N, ...) -> (exit code, json record, stdout text)

Reuses scope.py (change collection + component comparison), components.py (adapters) and
refs.py (symbol extraction, dangling verdicts). Knows nothing about the runner (engine/).
"""
from __future__ import annotations

import datetime as dt
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import refs
from components import FILE, IMPORTS, PSEUDO, adapter_for, base_qualname, decode_text
from scope import (EMPTY_TREE, OUT_OF_SCOPE, Scope, classify, collect_changes, ensure_repo,
                   git, git_text, norm_path, parse_scope, parse_scope_notes)
from scope import load_config as scope_load_config

SCHEMA_VERSION = 1
PASS, FAIL, MISCONFIGURED = 0, 1, 2
ERROR, WARN, INFO = "ERROR", "WARN", "INFO"

DEFAULT_SECTIONS = ["In short", "Problem and constraints", "Approach", "Alternatives considered",
                    "Trade-offs", "Key parameters", "Assumptions", "Edge cases", "Changes outside the scope",
                    "How it was verified", "To change this", "Rollback"]
DEFAULT_CONFIG = {"mode": "enforce", "dir": "docs/decisions",
                  "required_sections": DEFAULT_SECTIONS, "min_words": 150, "max_words": 3000}
STATUSES = ("implemented", "partial", "blocked")
BEGIN = "<!-- verified-facts:begin (generated by integrity record; do not edit) -->"
END = "<!-- verified-facts:end -->"
KNOWN_EXTS = {".py", ".pyi", ".php", ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx", ".dart",
              ".sql", ".ino", ".c", ".h", ".cc", ".cpp", ".hpp", ".md", ".txt", ".rst", ".json",
              ".yaml", ".yml", ".toml", ".ini", ".cfg", ".env", ".html", ".css", ".sh", ".ps1",
              ".go", ".rs", ".java", ".kt", ".cs", ".rb", ".swift", ".vue", ".svelte", ".xml",
              ".csv", ".xlsx", ".docx", ".pptx", ".lock", ".example"}
WAIVER_RE = re.compile(r"^(none|n/?a|not applicable|not checked)\b",
                       re.IGNORECASE)
COMP_REF_RE = re.compile(r"(?<![\w/.\-])([\w.\-]+(?:/[\w.\-]+)*\.[A-Za-z0-9]+|[\w.\-]+(?:/[\w.\-]+)+)"
                         r"::([A-Za-z_<][\w.<>#]*)")
BACKTICK_RE = re.compile(r"`([^`\n]+)`")
TEST_NAME_RE = re.compile(r"(?<![\w/.:])(test_\w+)\b(?!\.\w)")


def _now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


# ---------------------------------------------------------------------------
# config
# ---------------------------------------------------------------------------

def load_config(path: Optional[Path]) -> dict:
    """The "record" section of a project config JSON; missing file/section -> defaults."""
    cfg = {k: (list(v) if isinstance(v, list) else v) for k, v in DEFAULT_CONFIG.items()}
    if path is None or not Path(path).is_file():
        return cfg
    data = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError("config root must be a JSON object")
    sec = data.get("record", {})
    if not isinstance(sec, dict):
        raise ValueError('"record" section must be an object')
    for k, v in sec.items():
        if k.startswith("//") or k.startswith("_"):
            continue
        if k not in DEFAULT_CONFIG:
            raise ValueError(f"unknown record config key {k!r}")
        cfg[k] = v
    if cfg["mode"] not in ("report", "enforce"):
        raise ValueError(f"record.mode must be 'report' or 'enforce', not {cfg['mode']!r}")
    if not isinstance(cfg["dir"], str) or not cfg["dir"].strip():
        raise ValueError("record.dir must be a non-empty string")
    rs = cfg["required_sections"]
    if not isinstance(rs, list) or not all(isinstance(x, str) and x.strip() for x in rs):
        raise ValueError("record.required_sections must be a list of strings")
    for k in ("min_words", "max_words"):
        if not isinstance(cfg[k], int) or isinstance(cfg[k], bool) or cfg[k] < 0:
            raise ValueError(f"record.{k} must be a non-negative integer")
    return cfg


# ---------------------------------------------------------------------------
# facts block (string level; newline style preserved)
# ---------------------------------------------------------------------------

def split_facts(text: str) -> tuple[str, Optional[str], str]:
    """-> (before, block incl. markers and its line ending, after). block None if absent."""
    b = text.find(BEGIN)
    if b < 0:
        return text, None, ""
    ls = text.rfind("\n", 0, b) + 1               # start of the marker's line
    e = text.find(END, b)
    if e < 0:                                     # unterminated: treat the rest as the block
        return text[:ls], text[ls:], ""
    end = e + len(END)
    if text.startswith("\r\n", end):
        end += 2
    elif text.startswith("\n", end):
        end += 1
    return text[:ls], text[ls:end], text[end:]


def rationale_of(text: str) -> str:
    before, _, after = split_facts(text)
    return (before + after).replace("\r\n", "\n")


def _decode_record(data: bytes) -> tuple[str, str]:
    """Decode a record as UTF-8, else the Windows ANSI code page agents often write
    (PowerShell Set-Content), so an encoding never crashes the gate. Returns (text, encoding)."""
    try:
        return data.decode("utf-8"), "utf-8"
    except UnicodeDecodeError:
        try:
            return data.decode("cp1252"), "cp1252"
        except UnicodeDecodeError:
            return data.decode("latin-1"), "latin-1"


def _record_text(data: Optional[bytes]) -> Optional[str]:
    """A decision record's text with LF newlines; tolerant of non-UTF-8 encodings."""
    if data is None:
        return None
    if data.startswith(b"\xef\xbb\xbf"):
        data = data[3:]
    return _decode_record(data)[0].replace("\r\n", "\n").replace("\r", "\n")


def with_facts(data: bytes, block_lines: list[str]) -> bytes:
    """Replace (or append) the facts block; bytes outside the markers stay identical."""
    bom = data.startswith(b"\xef\xbb\xbf")
    text, enc = _decode_record(data[3:] if bom else data)
    nl = "\r\n" if "\r\n" in text else "\n"
    block = nl.join([BEGIN] + block_lines + [END]) + nl
    before, old, after = split_facts(text)
    if old is None:
        if before and not before.endswith("\n"):
            before += nl
        if before.strip():
            before += nl                          # one blank line before the block
        out = before + block
    else:
        out = before + block + after
    return (b"\xef\xbb\xbf" if bom else b"") + out.encode(enc, "replace")


# ---------------------------------------------------------------------------
# markdown parsing
# ---------------------------------------------------------------------------

@dataclass
class Parsed:
    title: str = ""
    status_raw: Optional[str] = None
    status: Optional[str] = None
    sections: list[tuple[str, str]] = field(default_factory=list)   # (heading, body)
    words: int = 0


def _norm_heading(h: str) -> str:
    h = re.sub(r"[*_`]", "", h).strip().lower()
    return re.sub(r"\s+", " ", h).rstrip(":").strip()


def parse_markdown(text: str) -> Parsed:
    p = Parsed()
    cur: Optional[list] = None
    fenced = False
    pre: list[str] = []
    for line in text.split("\n"):
        if line.lstrip().startswith(("```", "~~~")):
            fenced = not fenced
        if not fenced and re.match(r"^##\s+\S", line) and not line.startswith("###"):
            cur = [line[2:].strip(), []]
            p.sections.append(cur)  # type: ignore[arg-type]
            continue
        if not fenced and re.match(r"^#\s+\S", line) and cur is None and not p.title:
            p.title = line[1:].strip()
            continue
        (cur[1] if cur is not None else pre).append(line)
    p.sections = [(h, "\n".join(b).strip()) for h, b in p.sections]
    for line in pre:
        m = re.search(r"\bstatus\s*\**\s*:\s*\**\s*([A-Za-z]+)(\s*\|)?", line, re.IGNORECASE)
        if m:
            p.status_raw = line.strip()
            v = m.group(1).lower()
            p.status = v if v in STATUSES and not m.group(2) else None
            break
    p.words = len(re.findall(r"[A-Za-z0-9][\w'’.:/-]*", text))
    return p


def find_section(p: Parsed, name: str) -> Optional[tuple[str, str]]:
    want = _norm_heading(name)
    for h, body in p.sections:
        if _norm_heading(h).startswith(want):
            return h, body
    return None


def is_waiver(body: str) -> bool:
    s = " ".join(re.sub(r"^\s*(?:[-*>]|\d+\.)\s*", "", ln) for ln in body.split("\n")).strip()
    if not s:
        return True
    return bool(WAIVER_RE.match(s)) and len(s.split()) <= 12


# ---------------------------------------------------------------------------
# trees
# ---------------------------------------------------------------------------

class Trees:
    def __init__(self, repo: Path, old_rev: str, new_rev: Optional[str]):
        self.repo, self.old_rev, self.new_rev = repo, old_rev, new_rev
        self._ex: dict = {}
        self._bytes: dict = {}

    def exists(self, path: str, side: str) -> bool:
        key = (path, side)
        if key not in self._ex:
            rev = self.old_rev if side == "old" else self.new_rev
            if rev is None:
                self._ex[key] = (self.repo / path).exists()
            elif rev == EMPTY_TREE:
                self._ex[key] = False
            else:
                self._ex[key] = git(self.repo, "cat-file", "-e", f"{rev}:{path.rstrip('/')}",
                                    check=False).returncode == 0
        return self._ex[key]

    def read(self, path: str, side: str) -> Optional[bytes]:
        key = (path, side)
        if key not in self._bytes:
            rev = self.old_rev if side == "old" else self.new_rev
            if rev is None:
                f = self.repo / path
                self._bytes[key] = f.read_bytes() if f.is_file() else None
            elif rev == EMPTY_TREE:
                self._bytes[key] = None
            else:
                p = git(self.repo, "show", f"{rev}:{path}", check=False)
                self._bytes[key] = p.stdout if p.returncode == 0 else None
        return self._bytes[key]

    def qualnames(self, path: str, side: str) -> Optional[set[str]]:
        data = self.read(path, side)
        if data is None:
            return None
        parsed = adapter_for(path).parse(data, path)
        if parsed.error:
            return None
        return {base_qualname(c.qualname) for c in parsed.components} | set(PSEUDO)

    def list_dir(self, d: str) -> list[str]:
        d = norm_path(d).rstrip("/")
        if self.new_rev is None:
            base = self.repo / d
            return sorted(f"{d}/{x.name}" for x in base.iterdir() if x.is_file()) \
                if base.is_dir() else []
        out = git_text(self.repo, "ls-tree", "--name-only", self.new_rev, "--", d + "/")
        return sorted(norm_path(x) for x in out.splitlines() if x.strip())

    # -- path resolution: records often name paths relative to a subproject
    #    (`koi/x.py` for `Backend/koi/x.py`) or as bare file names (`x.py`).
    def tracked(self) -> tuple[set, set]:
        """(files, dirs) present in the old or the new tree."""
        if not hasattr(self, "_tracked"):
            files: set = set()
            for rev in (self.old_rev, self.new_rev):
                if rev == EMPTY_TREE:
                    continue
                if rev is None:
                    out = git_text(self.repo, "ls-files", "-co", "--exclude-standard")
                else:
                    out = git_text(self.repo, "ls-tree", "-r", "--name-only", rev)
                files.update(norm_path(x) for x in out.splitlines() if x.strip())
            dirs = {f.rsplit("/", i)[0] for f in files for i in range(1, f.count("/") + 1)}
            self._tracked = (files, dirs)
            self._res: dict = {}
        return self._tracked

    def resolve(self, ref: str, comp: Optional[str] = None) -> tuple[str, list[str]]:
        """-> (status, repo paths). status: exact | suffix | ambiguous | missing.
        exact: the path exists from the repo root; suffix: exactly one tracked path ends with
        it (segment aligned), or several do and some hold `comp` (those are returned);
        ambiguous: several match and `comp` does not disambiguate."""
        ref = norm_path(ref)
        files, dirs = self.tracked()
        key = (ref, comp)
        if key in self._res:
            return self._res[key]
        r = ref.rstrip("/")
        if r in files or r in dirs or self.exists(r, "old") or self.exists(r, "new"):
            res = ("exact", [r])
        else:
            pool = dirs if ref.endswith("/") else files | dirs
            m = sorted(x for x in pool if x.endswith("/" + r))
            if not m:
                res = ("missing", [])
            elif len(m) == 1:
                res = ("suffix", m)
            else:
                hold = [x for x in m if comp is not None and self.has_comp(x, comp)]
                res = ("suffix", hold) if hold else ("ambiguous", m)
        self._res[key] = res
        return res

    def has_comp(self, path: str, q: str) -> bool:
        if adapter_for(path).name == "file":
            return True
        names = (self.qualnames(path, "old") or set()) | (self.qualnames(path, "new") or set())
        return base_qualname(q) in names

    def aliases(self, path: str) -> list[str]:
        """`path` and every segment-aligned suffix of it that resolves to it alone."""
        parts = path.split("/")
        out = [path]
        for i in range(1, len(parts)):
            sfx = "/".join(parts[i:])
            st, ps = self.resolve(sfx)
            if st == "suffix" and ps == [path]:
                out.append(sfx)
        return out


# ---------------------------------------------------------------------------
# mentions
# ---------------------------------------------------------------------------

def comp_refs(text: str) -> list[tuple[str, str]]:
    out = []
    for m in COMP_REF_RE.finditer(text):
        q = m.group(2).rstrip(".")
        out.append((norm_path(m.group(1)), q))
    return list(dict.fromkeys(out))


def path_refs(text: str) -> list[str]:
    """Backticked repo-relative file paths (contain `/` or end in a known extension)."""
    out = []
    for m in BACKTICK_RE.finditer(text):
        s = m.group(1).strip()
        if "::" in s or any(c in s for c in " *?<>{}()[]|$=,;\"'") or "://" in s:
            continue
        s = re.sub(r":\d+(?:-\d+)?$", "", s)
        s = norm_path(s)
        if not re.fullmatch(r"[\w.\-/]+", s) or not re.search(r"[A-Za-z]", s) or s in (".", ".."):
            continue
        if s.startswith("/") or s.startswith("-") or ".." in s.split("/"):
            continue
        ext = Path(s.rstrip("/")).suffix.lower()
        if "/" in s.strip("/") or (ext in KNOWN_EXTS and not re.fullmatch(r"\.\w+", s)):
            out.append(s)
    return list(dict.fromkeys(out))


BRACE_RE = re.compile(r"([\w.\-/]*)\{([\w.\-]+(?:,[\w.\-]+)+)\}([\w.\-/]*)")


def expand_braces(text: str) -> str:
    """`text` plus, on extra lines, the expansions of shell-style path groups such as
    `storage/{base,memory}.py` (-> storage/base.py, storage/memory.py)."""
    extra = []
    for m in BRACE_RE.finditer(text):
        extra += ["`" + m.group(1) + x + m.group(3) + "`" for x in m.group(2).split(",")]
    return text + ("\n" + "\n".join(extra) if extra else "")


def path_mentioned(text: str, path: str) -> bool:
    """`path` appears on its own (not as the `path::` prefix of a component reference)."""
    return bool(re.search(r"(?<![\w/.\-])" + re.escape(path) + r"(?![\w/\-]|::|\.\w)", text))


def resolve_refs(refs_: list[tuple[str, str]], trees: "Trees") -> list[tuple[str, str]]:
    """Component references plus their paths resolved to repo paths (Trees.resolve)."""
    out = []
    for p, q in refs_:
        out.append((p, q))
        st, ps = trees.resolve(p, q)
        if st in ("exact", "suffix"):
            out += [(x, q) for x in ps]
    return list(dict.fromkeys(out))


def comp_mentioned(text: str, refs_: list[tuple[str, str]], path: str, q: str,
                   old_path: Optional[str] = None, removed: bool = False,
                   trees: Optional["Trees"] = None) -> bool:
    """Mentioned as `path::Name` (or an enclosing `path::Class`), or by its bare file path.
    A removed component also counts when its bare name is mentioned (it no longer exists,
    so there is nothing else to call it)."""
    paths = {path} | ({old_path} if old_path else set())
    spellings = set(paths)
    if trees is not None:
        for p in paths:
            spellings.update(trees.aliases(p))
    if any(path_mentioned(text, p) for p in spellings):
        return True
    if removed and q not in PSEUDO:
        leaf = base_qualname(q).rsplit(".", 1)[-1]
        if re.search(r"(?<![\w$])" + re.escape(leaf) + r"(?![\w$])", text):
            return True
    if q in PSEUDO:              # whole file / module-level code: any `path::X` covers it
        return any(p in paths for p, _ in refs_)
    bq = base_qualname(q)
    for p, mq in refs_:
        if p in paths and (bq == mq or bq.startswith(mq + ".")):
            return True
    # file-anchored short form: the record names the file as `path::X` somewhere and this
    # component as a backticked bare name (`GCC_MIN`, `Class.method`)
    if any(p in paths for p, _ in refs_):
        leaf = bq.rsplit(".", 1)[-1]
        parts = bq.split(".")
        enclosing = {".".join(parts[:i]) for i in range(1, len(parts))}   # `Class` covers its methods
        for name in {bq, leaf} | enclosing:
            if re.search(r"`" + re.escape(name) + r"(?:\(\))?`", text):
                return True
    return False


def _label(path: str, q: str) -> str:
    return path if q == FILE else f"{path}::{q}"


# ---------------------------------------------------------------------------
# removed symbols
# ---------------------------------------------------------------------------

def removed_symbols(cs, trees: Trees) -> list[dict]:
    """Symbols the old side of a changed file defines that no changed file defines any more."""
    new_defs: dict = {}
    for c in cs.changes:
        if c.change == "removed":
            continue
        fam = refs.family(c.path)
        txt = refs._decode(trees.read(c.path, "new"))
        new_defs.setdefault(fam, set()).update(refs.defined_names(c.path, txt)[1])
    out, seen = [], set()
    for c in cs.changes:
        if c.change == "added":
            continue
        src = c.old_path or c.path
        if refs.hit_class(src) in ("test", "doc"):
            continue
        old_syms = refs.extract(src, refs._decode(trees.read(src, "old")))
        if not old_syms:
            continue
        new_syms = set() if c.change == "removed" else \
            refs.extract(c.path, refs._decode(trees.read(c.path, "new")))
        new_names = {s.name for s in new_syms}
        gone_classes = {s.name for s in old_syms if s.kind == "class"} - new_names
        for s in sorted(old_syms, key=lambda s: s.display):
            if s.kind == "variable" or s.name in new_names:
                continue
            if s.kind == "method" and s.display.split(".")[0] in gone_classes:
                continue
            if s.name in new_defs.get(refs.family(src), set()):
                continue                                   # moved to another changed file
            if (src, s.display) in seen:
                continue
            seen.add((src, s.display))
            out.append({"symbol": s.display, "name": s.name, "kind": s.kind, "path": src})
    return out


# ---------------------------------------------------------------------------
# the check
# ---------------------------------------------------------------------------

def _finding(sev, code, msg, ref="") -> dict:
    return {"severity": sev, "code": code, "message": msg, "ref": ref}


def _result_status(result_text: str) -> Optional[str]:
    st = None
    for line in (result_text or "").splitlines():
        m = re.match(r"^\s*\**STATUS\**\s*:\s*\**\s*([A-Za-z_]+)", line)
        if m:
            st = m.group(1).upper()
    return st


def _gates_passed() -> Optional[list[str]]:
    raw = os.environ.get("AGENT_GATES_PASSED")
    if raw is None:
        return None
    try:
        v = json.loads(raw)
    except json.JSONDecodeError:
        return None
    return [str(x) for x in v] if isinstance(v, list) else None


def _test_name_exists(repo: Path, rev: Optional[str], name: str) -> bool:
    args = ["grep", "-l", "-w", "-F", "-I", "-e", name]
    args += ["--untracked"] if rev is None else [rev]
    p = git(repo, *args, check=False)
    prefix = f"{rev}:" if rev else ""
    for ln in p.stdout.decode("utf-8", "replace").splitlines():
        path = norm_path(ln[len(prefix):] if prefix and ln.startswith(prefix) else ln)
        if refs.hit_class(path) == "test":
            return True
    return False


def check_record(repo: Path, *, cfg: dict, mode: Optional[str] = None,
                 commit: Optional[str] = None, issue: Optional[int] = None,
                 attempt: Optional[int] = None, issue_text: str = "", result_text: str = "",
                 record_dir: Optional[Path] = None, write: bool = True,
                 config_path: Optional[Path] = None, version: str = "0"
                 ) -> tuple[int, dict, str]:
    """-> (exit code, record, stdout). Raises GitError / RefsError / ValueError on misconfig."""
    started = _now()
    mode = mode or cfg["mode"]
    if mode not in ("report", "enforce"):
        raise ValueError(f"mode must be report|enforce, not {mode!r}")
    if issue is None:
        m = re.match(r"^\s*#\s*#(\d+)", issue_text or "")
        issue = int(m.group(1)) if m else None
    if issue is None:
        raise ValueError("issue number unknown: pass --issue or set AGENT_ISSUE_NUMBER")
    repo = ensure_repo(Path(repo))
    exclude = []
    if record_dir is not None:
        try:
            exclude.append(Path(record_dir).resolve().relative_to(repo.resolve()).as_posix())
        except ValueError:
            pass
    cs = collect_changes(repo, commit, tuple(exclude))
    trees = Trees(repo, cs.old_rev, cs.new_rev)
    base = git_text(repo, "rev-parse", "--short", cs.old_rev).strip() \
        if cs.old_rev != EMPTY_TREE else "(none)"
    commit_sha = cs.new_rev
    compared = (f"{commit_sha[:10]}^..{commit_sha[:10]}" if commit_sha
                else f"HEAD..working tree (base {base})")
    findings: list[dict] = []
    changed = {c.path: c for c in cs.changes}

    # 1. locate the record
    rdir = norm_path(cfg["dir"]).rstrip("/")
    cands = [p for p in trees.list_dir(rdir)
             if (m := re.match(r"^(\d+)-.+\.md$", p.rsplit("/", 1)[-1], re.IGNORECASE))
             and int(m.group(1)) == issue]
    rec_path: Optional[str] = None
    want = f"{rdir}/{issue:04d}-<slug>.md"
    action: list[str] = []
    if not cands:
        findings.append(_finding(ERROR, "record_missing", f"no decision record for issue #{issue} "
                                 f"in {rdir}/", want))
        action.append(f"create {want} following the 'Decision record' format in the project "
                      "rules")
    elif len(cands) > 1:
        findings.append(_finding(ERROR, "record_ambiguous",
                                 f"{len(cands)} decision records for issue #{issue}: "
                                 + ", ".join(cands), ", ".join(cands)))
        action.append(f"keep exactly one record for issue #{issue} ({want}); merge or delete "
                      "the others")
    else:
        rec_path = cands[0]
        ch = changed.get(rec_path)
        old_t = _record_text(trees.read(rec_path, "old")) if ch and ch.change != "added" \
            else None
        new_t = _record_text(trees.read(rec_path, "new")) or ""
        if ch is None or (old_t is not None and rationale_of(old_t) == rationale_of(new_t)):
            findings.append(_finding(ERROR, "record_not_updated",
                                     f"decision record not updated by this change: {rec_path}",
                                     rec_path))
            action.append(f"update {rec_path} so it describes this change (a retry updates the "
                          "same file)")

    parsed = Parsed()
    sections = {"present": [], "missing": [], "waived": []}
    coverage = {"changed_components": 0, "mentioned": 0, "unmentioned": []}
    oos_info = {"total": 0, "explained": 0, "items": []}
    removed_info = {"total": 0, "mentioned": 0, "items": []}
    rows: list[dict] = []
    misc = {"tests": 0, "docs": 0}
    scope_declared = None
    scope_verdict = "no Scope line"
    text = ""
    usable = rec_path is not None and not any(f["code"] == "record_not_updated" for f in findings)
    if rec_path is not None:
        text = expand_braces(rationale_of(_record_text(trees.read(rec_path, "new")) or ""))
        parsed = parse_markdown(text)

    # changed components (classification with an empty scope)
    scfg = scope_load_config(config_path)
    files = classify(cs, Scope([]), scfg)
    rec_dirs = [rdir + "/"]
    comps = []
    for fr in files:
        for f in fr.findings:
            if f.component == IMPORTS:
                continue
            cls = refs.hit_class(fr.path)
            is_record = fr.path == rec_path
            testdoc = (cls in ("test", "doc") or f.reason == "allow_glob"
                       or fr.path.startswith(tuple(rec_dirs)))
            if testdoc or is_record:
                if not is_record:
                    misc["tests" if cls == "test" else "docs"] += 1
                continue
            chg = {"added": "new file", "removed": "deleted file", "renamed": "renamed"}.get(
                fr.change, "modified") if f.component == FILE else f.change
            row = {"path": fr.path, "component": f.component, "old_path": fr.old_path,
                   "label": _label(fr.path, f.component), "change": chg,
                   "added": f.lines_added, "removed": f.lines_removed, "tags": list(f.tags),
                   "description": f.description, "whitespace_only": f.whitespace_only,
                   "unparsed": f.category == "unverified"}
            rows.append(row)
            if f.component == FILE and fr.change == "added":     # list a new file's parts
                data = trees.read(fr.path, "new")
                pp = adapter_for(fr.path).parse(data or b"", fr.path)
                if not pp.error and not pp.whole_file:
                    for c in pp.components:
                        if c.parent is None or c.kind in ("method", "async_method"):
                            rows.append({"path": fr.path, "component": c.qualname,
                                         "old_path": None,
                                         "label": _label(fr.path, c.qualname), "change": "added",
                                         "added": c.span[1] - c.span[0] + 1, "removed": 0,
                                         "tags": list(c.tags), "description": c.description,
                                         "whitespace_only": False, "unparsed": False,
                                         "in_new_file": True})
            comps.append(row)

    if usable:
        # 2a. sections
        for name in cfg["required_sections"]:
            sec = find_section(parsed, name)
            if sec is None:
                sections["missing"].append(name)
                continue
            sections["present"].append(name)
            if is_waiver(sec[1]):
                sections["waived"].append(name)
        if sections["missing"]:
            findings.append(_finding(ERROR, "section_missing", "missing section(s): "
                                     + ", ".join(sections["missing"]),
                                     ", ".join(sections["missing"])))
            action.append(f"add the missing section(s) to {rec_path}: "
                          + ", ".join(f"## {s}" for s in sections["missing"])
                          + " (write 'None' or 'Not applicable' if there is nothing to say)")
        for name in sections["waived"]:
            findings.append(_finding(INFO, "section_waived", f"section '{name}' is waived "
                                     "(None / N/A / Not checked)", name))
        # 2b. status
        if parsed.status is None:
            findings.append(_finding(ERROR, "status_invalid",
                                     "Status line missing" if parsed.status_raw is None else
                                     f"Status must be one of implemented|partial|blocked: "
                                     f"{parsed.status_raw!r}", parsed.status_raw or ""))
            action.append(f"put one line under the title of {rec_path}: 'Status: implemented' "
                          "(or partial / blocked) · Issue: #N · Date: YYYY-MM-DD")
        # 2c. length
        if not (cfg["min_words"] <= parsed.words <= cfg["max_words"]):
            findings.append(_finding(WARN, "word_count",
                                     f"record has {parsed.words} words (expected "
                                     f"{cfg['min_words']}-{cfg['max_words']})", str(parsed.words)))
        # 2d. status vs agent result
        rs = _result_status(result_text)
        if rs and parsed.status:
            if (rs == "COMPLETE") != (parsed.status == "implemented"):
                findings.append(_finding(WARN, "status_mismatch",
                                         f"record says Status: {parsed.status} but the agent "
                                         f"result says STATUS: {rs}", rs))
        # 2e. verification claims
        flagged: set[str] = set()
        ver = find_section(parsed, "How it was verified")
        if ver:
            body = ver[1]
            for pth in path_refs(body) + [p for p, _ in comp_refs(body)]:
                if refs.hit_class(pth) == "test" and pth not in flagged \
                        and trees.resolve(pth)[0] == "missing":
                    flagged.add(pth)
                    findings.append(_finding(WARN, "verify_missing", "'How it was verified' names "
                                             f"a test file that does not exist: {pth}", pth))
            for name in dict.fromkeys(TEST_NAME_RE.findall(body)):
                if not _test_name_exists(repo, cs.new_rev, name):
                    flagged.add(name)
                    findings.append(_finding(WARN, "verify_missing", "'How it was verified' names "
                                             f"a test that does not exist: {name}", name))
        # 2f. references to code that does not exist
        crefs = comp_refs(text)
        for pth, q in crefs:
            lab = f"{pth}::{q}"
            if pth in flagged or lab in flagged:
                continue
            st, ps = trees.resolve(pth, q)
            if st == "missing":
                flagged.add(pth)
                findings.append(_finding(WARN, "ref_missing", "references something that doesn't "
                                         f"exist: {lab} (no such file)", lab))
                continue
            if st == "ambiguous":
                flagged.add(lab)
                findings.append(_finding(WARN, "ref_ambiguous", f"ambiguous reference: {lab} "
                                         f"matches {len(ps)} files ({', '.join(ps[:4])}) and none "
                                         "defines it; use the repo-relative path", lab))
                continue
            if not any(trees.has_comp(x, q) for x in ps):
                flagged.add(lab)
                findings.append(_finding(WARN, "ref_missing", "references something that doesn't "
                                         f"exist: {lab} (no such component in the old or new "
                                         "version)", lab))
        for pth in path_refs(text):
            if pth in flagged or pth.rstrip("/") in flagged:
                continue
            st, ps = trees.resolve(pth)
            if st == "missing":
                flagged.add(pth)
                findings.append(_finding(WARN, "ref_missing", "references something that doesn't "
                                         f"exist: {pth}", pth))
            elif st == "ambiguous" and not set(ps) & set(changed):
                flagged.add(pth)
                findings.append(_finding(WARN, "ref_ambiguous", f"ambiguous reference: {pth} "
                                         f"matches {len(ps)} files ({', '.join(ps[:4])}); use "
                                         "the repo-relative path", pth))
        # 2g. coverage
        rrefs = resolve_refs(crefs, trees)
        for row in comps:
            if row["whitespace_only"]:
                continue
            coverage["changed_components"] += 1
            if row.get("component") == FILE and row["change"] == "new file":
                # any mention of a new file (any unique spelling), incl. path::Name
                ok = any(re.search(r"(?<![\w/.\-])" + re.escape(a) + r"(?![\w\-])", text)
                         for a in trees.aliases(row["path"]))
            else:
                ok = comp_mentioned(text, rrefs, row["path"], row["component"], row["old_path"],
                                    removed=row["change"] == "removed", trees=trees)
            if ok:
                coverage["mentioned"] += 1
            else:
                coverage["unmentioned"].append(row["label"])
                findings.append(_finding(WARN, "unmentioned_change", f"{row['label']} "
                                         f"({row['change']}) changed but not mentioned in the "
                                         "record", row["label"]))
    # 2h. out of scope
    scope = parse_scope(issue_text or "")
    if scope is not None:
        scope_declared = scope.as_list()
        sfiles = classify(cs, scope, scfg, parse_scope_notes(result_text))
        oos = [f for fr in sfiles for f in fr.findings if f.category == OUT_OF_SCOPE]
        scope_verdict = "violation" if oos else "pass"
        sec = find_section(parsed, "Changes outside the scope") if usable else None
        stext = sec[1] if sec else ""
        srefs = resolve_refs(comp_refs(stext), trees)
        olds = {fr.path: fr.old_path for fr in sfiles}
        for f in oos:
            lab = f.target
            ok = comp_mentioned(stext, srefs, f.path, f.component, olds.get(f.path),
                                removed=f.change == "removed", trees=trees) if usable else False
            oos_info["total"] += 1
            oos_info["explained"] += int(ok)
            oos_info["items"].append({"target": lab, "explained": ok, "change": f.change})
            if usable and not ok:
                findings.append(_finding(WARN, "oos_unexplained", f"out-of-scope change not "
                                         f"explained in 'Changes outside the scope': {lab}", lab))
    # 2i. removed symbols
    rcfg = refs.load_config(config_path)
    rem = removed_symbols(cs, trees)
    dang, _ = refs.find_dangling(repo, commit, rcfg, tuple(exclude))
    sev = {(r.path, r.sym.display): r for r in dang}
    for r in rem:
        d = sev.get((r["path"], r["symbol"]))
        r["refs"] = d.severity if d else "unreferenced"
        r["code_hits"] = sum(1 for h in d.hits if h["class"] in ("code", "test")) if d else 0
        r["mentioned"] = bool(usable and (re.search(r"(?<![\w$])" + re.escape(r["name"])
                                                    + r"(?![\w$])", text)))
        removed_info["total"] += 1
        removed_info["mentioned"] += int(r["mentioned"])
        removed_info["items"].append(r)
        if usable and not r["mentioned"]:
            findings.append(_finding(WARN, "removed_unmentioned", f"removed {r['kind']} "
                                     f"{r['symbol']} (from {r['path']}) without mentioning it",
                                     f"{r['path']}::{r['symbol']}"))

    seen_msgs: set = set()                        # the same message once
    findings = [f for f in findings
                if not (f["message"] in seen_msgs or seen_msgs.add(f["message"]))]
    counts = {s: sum(1 for f in findings if f["severity"] == s) for s in (ERROR, WARN, INFO)}
    verdict = "fail" if counts[ERROR] else "pass"

    # 3. facts block
    gates = _gates_passed()
    facts = render_facts(issue=issue, attempt=attempt, compared=compared, rows=rows, misc=misc,
                         removed=removed_info["items"], scope_declared=scope_declared,
                         scope_verdict=scope_verdict, oos=oos_info["items"], gates=gates,
                         counts=counts, findings=findings, rec_path=rec_path or want,
                         commit_mode=commit is not None)
    facts_written = False
    if write and commit is None and usable:
        f = repo / rec_path
        data = f.read_bytes()
        new = with_facts(data, facts)
        if new != data:
            f.write_bytes(new)
        facts_written = True

    rec = {"schema_version": SCHEMA_VERSION, "tool": "integrity record", "tool_version": version,
           "issue": issue, "attempt": attempt, "commit": commit_sha, "compared": compared,
           "mode": mode, "verdict": verdict, "record_path": rec_path,
           "word_count": parsed.words if rec_path else 0,
           "status": parsed.status, "result_status": _result_status(result_text),
           "sections": sections, "findings": findings, "counts": counts,
           "coverage": coverage,
           "out_of_scope": {"total": oos_info["total"], "explained": oos_info["explained"],
                            "items": oos_info["items"]},
           "removed_symbols": {"total": removed_info["total"],
                               "mentioned": removed_info["mentioned"],
                               "items": removed_info["items"]},
           "scope_declared": scope_declared, "gates_passed": gates,
           "facts_written": facts_written, "started": started, "finished": _now()}
    out = render_stdout(rec, action)
    if commit is not None:
        out += "\n\n" + "\n".join([BEGIN] + facts + [END])
    elif facts_written:
        out += f"\n(verified facts written to {rec_path})"
    if record_dir is not None:
        record_dir = Path(record_dir)
        record_dir.mkdir(parents=True, exist_ok=True)
        stem = (f"record_issue-{issue}_attempt-{attempt if attempt is not None else 0}"
                if commit is None else f"record_commit-{commit_sha[:10]}")
        (record_dir / f"{stem}.json").write_text(json.dumps(rec, indent=2), encoding="utf-8")
        out += f"\n(record: {record_dir / (stem + '.json')})"
    rc = FAIL if verdict == "fail" and mode == "enforce" else PASS
    return rc, rec, out


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

def _cell(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ").strip()


def render_facts(*, issue, attempt, compared, rows, misc, removed, scope_declared,
                 scope_verdict, oos, gates, counts, findings, rec_path, commit_mode) -> list[str]:
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    att = f" attempt {attempt}" if attempt is not None else ""
    L = ["## Verified facts", "",
         f"Generated {ts} for issue #{issue}{att}; compared {compared}.", "",
         "**Changed components**", ""]
    if rows:
        L += ["| Component | Change | Lines +/- | Tags | Description |", "|---|---|---|---|---|"]
        for r in rows:
            chg = r["change"] + (" (whitespace only)" if r["whitespace_only"] else "") + \
                (" (could not parse)" if r["unparsed"] else "") + \
                (f" (from {r['old_path']})" if r.get("old_path") and r["change"] == "renamed"
                 else "")
            L.append(f"| `{_cell(r['label'])}` | {chg} | +{r['added']}/-{r['removed']} | "
                     f"{_cell(', '.join(r['tags']))} | {_cell(r['description'])} |")
    else:
        L.append("No code components changed.")
    extra = [f"{misc['tests']} test file(s)" if misc["tests"] else "",
             f"{misc['docs']} doc file(s)" if misc["docs"] else ""]
    extra = [x for x in extra if x]
    if extra:
        L += ["", "Plus " + ", ".join(extra) + "."]
    L += ["", "**Removed symbols**", ""]
    if removed:
        verdict = {"dangling": "STILL REFERENCED in code", "doc_only": "referenced in docs only",
                   "unreferenced": "no remaining references"}
        for r in removed:
            L.append(f"- `{r['path']}::{r['symbol']}` ({r['kind']}): "
                     f"{verdict.get(r['refs'], r['refs'])}")
    else:
        L.append("None.")
    L += ["", "**Scope**", ""]
    if scope_declared is None:
        L.append("No Scope line in the issue.")
    else:
        L.append("Declared: " + (", ".join(f"`{s}`" for s in scope_declared) or "(empty)")
                 + f". Verdict: {scope_verdict}.")
        for o in oos:
            L.append(f"- out of scope: `{o['target']}` ({o['change']}); explained in the record: "
                     f"{'yes' if o['explained'] else 'no'}")
    L += ["", "**Supervisor checks passed**", ""]
    L.append(", ".join(gates) if gates else ("none" if gates == [] else "not available"))
    L += ["", "**Consistency**", ""]
    L.append(f"{counts[ERROR]} error(s), {counts[WARN]} warning(s) between the rationale above "
             "and the change.")
    for f in findings:
        if f["severity"] in (ERROR, WARN):
            L.append(f"- {f['severity']}: {f['message']}")
    L += ["", "**Commit**", ""]
    L.append("This record is committed with the change it describes; "
             f"`git log -1 -- {rec_path}` gives the commit.")
    return L


def render_stdout(rec: dict, action: list[str]) -> str:
    c = rec["counts"]
    head = (f"DECISION RECORD: {rec['verdict'].upper()} ({rec['mode']} mode) - "
            f"{rec['record_path'] or 'no record'}: {c[ERROR]} error(s), {c[WARN]} warning(s), "
            f"{c[INFO]} info  [{rec['compared']}]")
    out = [head]
    errs = [f for f in rec["findings"] if f["severity"] == ERROR]
    warns = [f for f in rec["findings"] if f["severity"] == WARN]
    if errs:
        out.append("ERRORS (must fix):")
        out += [f"  - {f['message']}" for f in errs]
        out.append("ACTION: " + "; ".join(action) + ".")
    if warns:
        out.append("WARNINGS (not blocking; fix the record if it is wrong):")
        out += [f"  - {f['message']}" for f in warns[:30]]
        if len(warns) > 30:
            out.append(f"  ... {len(warns) - 30} more in the record")
    cov = rec["coverage"]
    out.append(f"coverage: {cov['mentioned']}/{cov['changed_components']} changed component(s) "
               f"mentioned; out-of-scope explained {rec['out_of_scope']['explained']}/"
               f"{rec['out_of_scope']['total']}; removed symbols mentioned "
               f"{rec['removed_symbols']['mentioned']}/{rec['removed_symbols']['total']}")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# self-tests (temp git repos) — called from `integrity.py self-test`
# ---------------------------------------------------------------------------

APP_SRC = '''"""App."""


# @tags: billing
def compute_total(items):
    """Sum the item prices."""
    return sum(items)


def old_helper(x):
    return x


def keep(x):
    return x
'''

GOOD_RECORD = """# 0007: Totals

Status: implemented · Issue: #7 · Date: 2026-10-09

## In short
The total now applies a discount. {filler}

## Problem and constraints
The issue asked for a discount on `src/app.py::compute_total`.

## Approach
`src/app.py::compute_total` multiplies by 0.9. old_helper was deleted because nothing used it.

## Alternatives considered
None considered.

## Trade-offs
Fixed discount rate; a configurable rate would matter for promotions.

## Key parameters
Discount factor 0.9, from the issue; raising it lowers the discount.

## Assumptions
- Prices are non-negative.

## Edge cases
- Handled: empty list gives 0.

## Changes outside the scope
None.

## How it was verified
Ran `tests/test_app.py` (test_total).

## To change this
Change the factor in `src/app.py::compute_total`.

## Rollback
Nothing depends on it.
"""


def self_test(check, integrity_py: str) -> None:
    import shutil
    filler = " ".join(["word"] * 160)
    # A record saved in the Windows ANSI code page (e.g. by PowerShell) must parse and keep its encoding.
    ansi = "# 0001: t\nStatus: implemented · Issue: #1\n## In short\ncafé\n".encode("cp1252")
    out = with_facts(ansi, ["## Verified facts", "x"])
    check("record: cp1252 record parsed and rewritten in cp1252",
          "Status: implemented" in (_record_text(ansi) or "") and out.startswith(ansi)
          and out.decode("cp1252").count(BEGIN) == 1, out[:80])
    with tempfile.TemporaryDirectory() as d:
        repo = Path(d) / "r"
        repo.mkdir()
        env = {k: v for k, v in os.environ.items() if not k.startswith("AGENT_")}
        env.update(GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@t", GIT_COMMITTER_NAME="t",
                   GIT_COMMITTER_EMAIL="t@t")

        def g(*a):
            return subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *a],
                                  cwd=repo, check=True, env=env, stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE).stdout.decode()

        def w(rel, text, crlf=False):
            f = repo / rel
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_bytes((text.replace("\n", "\r\n") if crlf else text).encode("utf-8"))

        def reset():
            g("reset", "-q", "--hard")
            g("clean", "-fdq")

        g("init", "-q")
        g("config", "core.autocrlf", "false")
        w("src/app.py", APP_SRC)
        w("tests/test_app.py", "def test_total():\n    assert True\n")
        w("docs/decisions/0003-old.md", "# 0003\n")
        g("add", "-A")
        g("commit", "-qm", "init")
        cfg = load_config(None)
        saved = os.environ.pop("AGENT_GATES_PASSED", None)

        def change_code():
            s = (repo / "src/app.py").read_text(encoding="utf-8")
            s = s.replace("return sum(items)", "return sum(items) * 0.9")
            s = s.replace("def old_helper(x):\n    return x\n\n\n", "")
            w("src/app.py", s)

        def run(**kw):
            kw.setdefault("issue", 7)
            kw.setdefault("cfg", cfg)
            rc, rec, text = check_record(repo, **kw)
            return rc, rec, text

        def codes(rec, sev=None):
            return [f["code"] for f in rec["findings"] if sev is None or f["severity"] == sev]

        try:
            # missing record
            change_code()
            rc, rec, text = run()
            check("record: missing record -> ERROR, exit 1 in enforce",
                  rc == FAIL and codes(rec, ERROR) == ["record_missing"]
                  and "docs/decisions/0007-<slug>.md" in text, text)
            rc, rec, _ = run(mode="report")
            check("record: missing record in report mode -> exit 0", rc == PASS
                  and rec["verdict"] == "fail")

            # record present but not updated by this change
            w("docs/decisions/0007-totals.md", GOOD_RECORD.format(filler=filler))
            g("add", "-A")
            g("commit", "-qm", "rec")
            change_code()
            rc, rec, text = run()
            check("record: present but unchanged -> ERROR record_not_updated",
                  rc == FAIL and "record_not_updated" in codes(rec, ERROR), text)
            reset()
            g("reset", "-q", "--hard", "HEAD~1")

            # good record
            change_code()
            w("docs/decisions/0007-totals.md", GOOD_RECORD.format(filler=filler))
            rc, rec, text = run(write=False)
            check("record: consistent record -> pass, no warnings",
                  rc == PASS and rec["verdict"] == "pass" and codes(rec, WARN) == []
                  and rec["coverage"]["mentioned"] == rec["coverage"]["changed_components"] == 2
                  and rec["removed_symbols"]["total"] == rec["removed_symbols"]["mentioned"] == 1,
                  [f["message"] for f in rec["findings"]])
            check("record: waived section counts as present + INFO",
                  "Alternatives considered" in rec["sections"]["waived"]
                  and "Alternatives considered" in rec["sections"]["present"]
                  and "section_waived" in codes(rec, INFO), rec["sections"])

            # missing section / bad status
            w("docs/decisions/0007-totals.md", GOOD_RECORD.format(filler=filler)
              .replace("## Rollback\nNothing depends on it.\n", "")
              .replace("Status: implemented", "Status: implemented | partial"))
            rc, rec, text = run(write=False)
            check("record: missing section -> ERROR, action names it",
                  rc == FAIL and "section_missing" in codes(rec, ERROR)
                  and rec["sections"]["missing"] == ["Rollback"] and "## Rollback" in text, text)
            check("record: bad Status -> ERROR", "status_invalid" in codes(rec, ERROR), text)

            # facts block: write, idempotent, CRLF preserved
            body = GOOD_RECORD.format(filler=filler)
            w("docs/decisions/0007-totals.md", body, crlf=True)
            os.environ["AGENT_GATES_PASSED"] = json.dumps(["Tests", "Scope gate"])
            try:
                rc, rec, _ = run(attempt=2)
            finally:
                os.environ.pop("AGENT_GATES_PASSED", None)
            data1 = (repo / "docs/decisions/0007-totals.md").read_bytes()
            t1 = data1.decode("utf-8")
            check("record: facts block written at end (CRLF kept, gates rendered)",
                  rec["facts_written"] and t1.startswith(body.replace("\n", "\r\n"))
                  and t1.rstrip().endswith(END) and "\n" not in t1.replace("\r\n", "")
                  and "Tests, Scope gate" in t1 and "issue #7 attempt 2" in t1
                  and "`src/app.py::compute_total`" in t1 and "billing" in t1, t1[-900:])
            rc, rec, _ = run(attempt=2)
            data2 = (repo / "docs/decisions/0007-totals.md").read_bytes()
            check("record: re-run replaces block idempotently",
                  data2.count(BEGIN.encode()) == 1 and data2.startswith(body.replace(
                      "\n", "\r\n").encode()) and "not available" in data2.decode()
                  and rec["verdict"] == "pass", data2[-300:])
            raw = body.replace("\n", "\r\n").encode()
            mid = with_facts(raw, ["x"]) + b"Trailer typed after the block\r\n"
            mid2 = with_facts(mid, ["y", "z"])
            b1, _, a1 = split_facts(mid.decode())
            b2, blk2, a2 = split_facts(mid2.decode())
            check("record: text outside markers byte-identical across rewrites",
                  b1 == b2 and a1 == a2 == "Trailer typed after the block\r\n"
                  and b2.startswith(raw.decode()) and "y\r\nz\r\n" in blk2, mid2)
            reset()

            # unmentioned change, nonexistent ref, removed symbol unmentioned, bad test
            change_code()
            s = (repo / "src/app.py").read_text(encoding="utf-8")
            w("src/app.py", s.replace("def keep(x):\n    return x", "def keep(x):\n    return -x"))
            rec_txt = (GOOD_RECORD.format(filler=filler)
                       .replace("old_helper was deleted because nothing used it.",
                                "See `src/app.py::ghost_fn` and `src/missing.py`.")
                       .replace("(test_total)", "(test_total, test_nonexistent_case) and "
                                "`tests/test_nope.py`"))
            w("docs/decisions/0007-totals.md", rec_txt)
            rc, rec, text = run(write=False)
            msgs = [f["message"] for f in rec["findings"] if f["severity"] == WARN]
            check("record: changed function not mentioned -> WARN",
                  "src/app.py::keep" in rec["coverage"]["unmentioned"] and rc == PASS, msgs)
            check("record: nonexistent path::Name and path -> WARN ref_missing",
                  any("src/app.py::ghost_fn" in m for m in msgs)
                  and any("src/missing.py" in m for m in msgs), msgs)
            check("record: removed symbol unmentioned -> WARN",
                  any("old_helper" in m and "without mentioning" in m for m in msgs)
                  and rec["removed_symbols"]["mentioned"] == 0, msgs)
            check("record: verification names nonexistent test -> WARN",
                  any("test_nonexistent_case" in m for m in msgs)
                  and any("tests/test_nope.py" in m and "verified" in m for m in msgs)
                  and not any("test_total" in m for m in msgs), msgs)

            # out of scope: explained vs unexplained
            reset()
            w("src/extra.py", "def z():\n    return 1\n")
            g("add", "-A")
            g("commit", "-qm", "extra")
            change_code()
            w("src/extra.py", "def z():\n    return 2\n")
            s = (repo / "src/app.py").read_text(encoding="utf-8")
            w("src/app.py", s.replace("def keep(x):\n    return x", "def keep(x):\n    return -x"))
            issue_text = "# #7 t\n\n**Scope:** `src/app.py::compute_total`\n"
            rt = GOOD_RECORD.format(filler=filler).replace(
                "## Changes outside the scope\nNone.",
                "## Changes outside the scope\n`src/app.py::keep` had to flip sign. "
                "Also touched src/extra.py::z and old_helper.")
            w("docs/decisions/0007-totals.md", rt)
            rc, rec, _ = run(write=False, issue_text=issue_text)
            o = rec["out_of_scope"]
            check("record: out-of-scope changes all explained -> counted",
                  o["total"] == 3 and o["explained"] == 3 and "oos_unexplained" not in codes(rec),
                  o)
            w("docs/decisions/0007-totals.md", rt.replace("Also touched src/extra.py::z and "
                                                          "old_helper.", ""))
            rc, rec, _ = run(write=False, issue_text=issue_text)
            o = rec["out_of_scope"]
            check("record: unexplained out-of-scope change -> WARN, counted",
                  o["total"] == 3 and o["explained"] == 1
                  and codes(rec, WARN).count("oos_unexplained") == 2, o)

            # status mismatch with result file
            res = "===AGENT_ISSUE_RESULT_BEGIN===\nSTATUS: BLOCKED\n===AGENT_ISSUE_RESULT_END===\n"
            rc, rec, _ = run(write=False, issue_text=issue_text, result_text=res)
            check("record: Status vs result STATUS mismatch -> WARN",
                  "status_mismatch" in codes(rec, WARN), codes(rec))
            reset()

            # --commit mode: never writes, prints the facts
            change_code()
            w("docs/decisions/0007-totals.md", GOOD_RECORD.format(filler=filler))
            g("add", "-A")
            g("commit", "-qm", "issue 7")
            sha = g("rev-parse", "HEAD").strip()
            w("docs/decisions/0007-totals.md", "dirty\n")
            rd = Path(d) / "rd"
            rc, rec, text = run(commit=sha, record_dir=rd)
            check("record --commit: no write, facts printed, record named by sha",
                  rc == PASS and not rec["facts_written"]
                  and (repo / "docs/decisions/0007-totals.md").read_text() == "dirty\n"
                  and BEGIN in text and "## Verified facts" in text
                  and (rd / f"record_commit-{sha[:10]}.json").is_file(), text)
            reset()

            # path resolution: subproject-relative, bare file name, ambiguous, braces
            w("Backend/koi/worker/poller.py", "def calibrate(x):\n    return x\n\n\n"
              "class Job:\n    def run(self):\n        return 1\n")
            w("Backend/koi/storage/base.py", "def save(x):\n    return x\n")
            w("Backend/koi/storage/memory.py", "def save(x):\n    return x\n")
            w("Backend/tests/test_calib.py", "def test_fit():\n    assert True\n")
            w("Backend/a/util.py", "def f():\n    return 1\n")
            w("Backend/b/util.py", "def g():\n    return 1\n")
            g("add", "-A")
            g("commit", "-qm", "backend")
            w("Backend/koi/worker/poller.py", "def calibrate(x):\n    return -x\n\n\n"
              "class Job:\n    def run(self):\n        return 2\n")
            w("Backend/koi/storage/base.py", "def save(x):\n    return -x\n")
            w("Backend/koi/storage/memory.py", "def save(x):\n    return -x\n")
            w("Backend/a/util.py", "def f():\n    return 2\n")
            rt = GOOD_RECORD.format(filler=filler).replace(
                "old_helper was deleted because nothing used it.",
                "`koi/worker/poller.py::calibrate` flips sign; `poller.py::calibrate` again; "
                "the `Job` class changed; `util.py::f` too; see `util.py::nope`, `util.py`, "
                "`storage/{base,memory}.py` and `worker/ghost.py`.").replace(
                "Ran `tests/test_app.py` (test_total).",
                "Ran `test_calib.py` and `tests/test_calib.py` (test_fit).")
            w("docs/decisions/0007-totals.md", rt)
            rc, rec, _ = run(write=False)
            msgs = [f["message"] for f in rec["findings"] if f["severity"] == WARN]
            check("record: subproject-relative and bare-file refs resolve (no ref_missing)",
                  not any("calibrate" in m or "test_calib" in m or "util.py::f" in m
                          for m in msgs) and any("worker/ghost.py" in m for m in msgs), msgs)
            check("record: ambiguous ref not holding the component -> WARN ambiguous",
                  any("ambiguous" in m and "util.py::nope" in m for m in msgs)
                  # bare `util.py` is ambiguous but one match changed -> accepted
                  and not any("ambiguous reference: util.py " in m for m in msgs), msgs)
            check("record: subproject-relative / bare / brace mentions count toward coverage",
                  not any("not mentioned" in m and "Backend/" in m for m in msgs)
                  and rec["coverage"]["mentioned"] == rec["coverage"]["changed_components"],
                  (rec["coverage"], msgs))
            check("record: duplicate WARN messages reported once",
                  len(msgs) == len(set(msgs)), msgs)
            reset()

            # CLI: env vars, JSON record schema, exit codes
            change_code()
            w("docs/decisions/0007-totals.md", GOOD_RECORD.format(filler=filler)
              .replace("## Rollback", "## Rollbak"))
            rundir = Path(d) / "run"
            cenv = dict(env, AGENT_ISSUE_NUMBER="7", AGENT_ATTEMPT="1", AGENT_RUN_DIR=str(rundir),
                        AGENT_GATES_PASSED='["Tests"]')
            cp = subprocess.run([sys.executable, integrity_py, "record"], cwd=repo, env=cenv,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            jf = rundir / "integrity" / "record_issue-7_attempt-1.json"
            j = json.loads(jf.read_text(encoding="utf-8")) if jf.is_file() else {}
            keys = {"schema_version", "verdict", "record_path", "word_count", "sections",
                    "findings", "counts", "coverage", "out_of_scope", "removed_symbols",
                    "facts_written"}
            check("record CLI: enforce default exit 1, JSON record with schema keys",
                  cp.returncode == 1 and keys <= set(j) and j["verdict"] == "fail"
                  and j["facts_written"] and "Tests" in (repo / "docs/decisions/0007-totals.md")
                  .read_text(encoding="utf-8"), cp.stdout + cp.stderr)
            (Path(d) / "bad.json").write_text('{"record": {"strict": 1}}', encoding="utf-8")
            cp = subprocess.run([sys.executable, integrity_py, "record", "--repo", str(repo),
                                 "--issue", "7", "--config", str(Path(d) / "bad.json")],
                                stdout=subprocess.PIPE, text=True, env=env)
            check("record CLI: unknown config key -> exit 2", cp.returncode == 2, cp.stdout)
            cp = subprocess.run([sys.executable, integrity_py, "record", "--repo", str(repo),
                                 "--no-write", "--mode", "report"],
                                stdout=subprocess.PIPE, text=True, env=env)
            check("record CLI: no issue number -> exit 2", cp.returncode == 2, cp.stdout)
            reset()
        finally:
            if saved is not None:
                os.environ["AGENT_GATES_PASSED"] = saved
        shutil.rmtree(Path(d) / "rd", ignore_errors=True)
